version: 1.0.0-{build}

image: Visual Studio 2022

configuration: Release

cache: 
    - packages -> **\packages.config

before_build: nuget restore

build_script:
  - ps: |
      # Instala las dependencias de .NET 7
      dotnet --list-sdks
      dotnet --version
      dotnet --list-runtimes
      
      # Compila la aplicación especificando el archivo de proyecto
      dotnet build LearningBlazorCRUD.csproj
  - publish_wap: true

deploy:
  - provider: Environment
    name: $APP_ENV
    on:
      branch: master

  - provider: FTP
    server: ftp://155.254.244.28/www.bookstorage.somee.com
    protocol: ftp
    username: yfelo820
    password: Rafa!@123
    folder: /
    source: /bin/Release/net7.0 # Carpeta de los archivos a cargar
    recursive: true
    replace: true # Esto indica que se deben reemplazar los archivos existentes
