version: 1.0.0-{build}
image: Visual Studio 2022
environment:
  matrix:
    - APP_ENV: Development
configuration: Release
cache:
  - packages -> **\packages.config
before_build: nuget restore
build_script:
  - ps: |
      # Instala las dependencias de .NET 7
      dotnet --list-sdks
      dotnet --version
      dotnet --list-runtimes

      # Compila la aplicación especificando el archivo de proyecto
      dotnet build LearningBlazorCRUD.csproj
artifacts:
  - path: /bin/Release/net7.0
    name: blazorapp
    type: zip
  - path: /wwwroot
    name: wwwfolder
    type: zip
deploy:
  - provider: Environment
    name: blazor_app_env
  - provider: Enviroment
    name: wwwfolder_app_env
    on:
      branch: master
